version: "3.3"
services:
  web:
    restart: always
    build: .
    ports:
      - "80:80"
    volumes: 
      - "./dist:/dist"
    depends_on:
      - mongo
  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes: 
      - ./mongo_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: auth